Fix Header on Mobile View. #51
alexa-dev-hub/alexa-community-jaipur pull request #73
Opened 2020-10-11 15:56 UTC by beatrizsmerino

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-11 18:24 UTC, tarunnsingh requested changes
### Everything works really well! Just while testing for responsiveness around 400px - 450px, this minor overlapping happens.
![image](https://user-images.githubusercontent.com/31896659/95686562-428bae00-0c1c-11eb-8a1f-945043b59b28.png)

### A Simple solution is to make media-query breakpoint at 450px instead of 400px, and it work superb!!.

![image](https://user-images.githubusercontent.com/31896659/95686597-6bac3e80-0c1c-11eb-86a4-5a3f3ba8dcc7.png)

### Please add a commit with this minor fix. And rest is cool! :fire:

2020-10-12 12:27 UTC, imabp commented
> ### Everything works really well! Just while testing for responsiveness around 400px - 450px, this minor overlapping happens.
> ![image](https://user-images.githubusercontent.com/31896659/95686562-428bae00-0c1c-11eb-8a1f-945043b59b28.png)
> 
> ### A Simple solution is to make media-query breakpoint at 450px instead of 400px, and it work superb!!.
> ![image](https://user-images.githubusercontent.com/31896659/95686597-6bac3e80-0c1c-11eb-86a4-5a3f3ba8dcc7.png)
> 
> ### Please add a commit with this minor fix. And rest is cool! 🔥

@beatrizsmerino

2020-10-12 13:32 UTC, tarunnsingh approved these changes

2020-10-12 13:32 UTC, merged

2020-10-12 13:34 UTC, tarunnsingh commented
@all-contributors please add @beatrizsmerino for code